# Generated by Django 4.1.4 on 2023-07-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atento_care', '0002_alter_scheduledappointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledappointment',
            name='doctor_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduledappointment',
            name='patient_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
