# Generated by Django 4.1.4 on 2023-07-21 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atento_care', '0004_doctoravailability_date_scheduledappointment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctoravailability',
            name='date',
        ),
    ]
