# Generated by Django 4.1.4 on 2023-07-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atento_care', '0005_remove_doctoravailability_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoravailability',
            name='day_of_week',
            field=models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')]),
        ),
    ]
