# Generated by Django 4.1.4 on 2023-07-25 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atento_care', '0006_alter_doctoravailability_day_of_week'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='doctoravailability',
            unique_together={('doctor', 'day_of_week')},
        ),
    ]
