# Generated by Django 4.1.4 on 2023-09-13 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atento_care', '0007_alter_doctoravailability_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppointmentStatus',
        ),
        migrations.AlterUniqueTogether(
            name='doctoravailability',
            unique_together={('doctor', 'day_of_week', 'start_time', 'end_time')},
        ),
    ]
