# Generated by Django 4.1.4 on 2023-09-16 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atento_care', '0009_doctoravailability_is_booked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctoravailability',
            name='is_booked',
        ),
    ]
