# Generated by Django 4.1.4 on 2023-10-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atento_care', '0010_remove_doctoravailability_is_booked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('', 'Please select a role'), ('DOCTOR', 'Doctor'), ('PATIENT', 'Patient')], default='', max_length=50),
        ),
    ]
